/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Codes.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Lenovo
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tambahPemilihPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        namaTextField = new javax.swing.JTextField();
        npmTextField = new javax.swing.JTextField();
        tambahButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dataPemilihPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        npmPemilihField = new javax.swing.JTextField();
        namaPemilihField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        updatePemilihButton = new javax.swing.JButton();
        hapusPemilihButton = new javax.swing.JButton();
        resetButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pemilihTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dataCalonPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        noUrutField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        namaCalonField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        visiMisiTextArea = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        updateCalonButton = new javax.swing.JButton();
        resetButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        calonTable = new javax.swing.JTable();
        fotoCalonField = new javax.swing.JLabel();
        cariCalonButton2 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dataSuaraPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        suaraTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        suaraCalon1Field = new javax.swing.JTextField();
        suaraCalon2Field = new javax.swing.JTextField();
        suaraCalon3Field = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1192, 625));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuPanel.setBackground(new java.awt.Color(249, 210, 82));
        menuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");
        menuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 108, 40));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setBorderPainted(false);
        jButton1.setDefaultCapable(false);
        jButton1.setEnabled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.setVerifyInputWhenFocusTarget(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 53, 108, -1));

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Tambah Pemilih");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 132, -1, -1));

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Data Pemilih");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 186, -1, -1));

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Home");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 78, -1, -1));

        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Data Calon");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 240, -1, -1));

        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Data Suara");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 294, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 0, 51));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Logout");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        menuPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, 40));

        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setMaximumSize(new java.awt.Dimension(2147483647, 600));
        homePanel.setMinimumSize(new java.awt.Dimension(0, 580));
        homePanel.setPreferredSize(new java.awt.Dimension(460, 580));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/welcomeadmin.png"))); // NOI18N
        homePanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        mainPanel.add(homePanel, "card2");

        tambahPemilihPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Imprint MT Shadow", 3, 36)); // NOI18N
        jLabel8.setText("Tambah Data Pemilih");
        tambahPemilihPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 380, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("NPM");
        tambahPemilihPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));
        tambahPemilihPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 230, -1));
        tambahPemilihPanel.add(namaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 230, -1));
        tambahPemilihPanel.add(npmTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 230, -1));

        tambahButton.setBackground(new java.awt.Color(193, 158, 44));
        tambahButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahButton.setText("Insert");
        tambahButton.setBorderPainted(false);
        tambahButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });
        tambahPemilihPanel.add(tambahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 100, 30));

        resetButton.setBackground(new java.awt.Color(153, 0, 0));
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.setBorderPainted(false);
        resetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        tambahPemilihPanel.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 100, 30));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Password");
        tambahPemilihPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Nama");
        tambahPemilihPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin.png"))); // NOI18N
        tambahPemilihPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(tambahPemilihPanel, "card3");

        dataPemilihPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText(":");
        dataPemilihPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        npmPemilihField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npmPemilihFieldActionPerformed(evt);
            }
        });
        dataPemilihPanel.add(npmPemilihField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 220, -1));

        namaPemilihField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPemilihFieldActionPerformed(evt);
            }
        });
        dataPemilihPanel.add(namaPemilihField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 220, -1));

        jLabel13.setText("Nama");
        dataPemilihPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        updatePemilihButton.setBackground(new java.awt.Color(51, 153, 0));
        updatePemilihButton.setForeground(new java.awt.Color(255, 255, 255));
        updatePemilihButton.setText("Update");
        updatePemilihButton.setBorderPainted(false);
        updatePemilihButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatePemilihButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePemilihButtonActionPerformed(evt);
            }
        });
        dataPemilihPanel.add(updatePemilihButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        hapusPemilihButton.setBackground(new java.awt.Color(51, 0, 51));
        hapusPemilihButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusPemilihButton.setText("Delete");
        hapusPemilihButton.setBorderPainted(false);
        hapusPemilihButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapusPemilihButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemilihButtonActionPerformed(evt);
            }
        });
        dataPemilihPanel.add(hapusPemilihButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));

        resetButton2.setBackground(new java.awt.Color(153, 0, 0));
        resetButton2.setForeground(new java.awt.Color(255, 255, 255));
        resetButton2.setText("Reset");
        resetButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton2ActionPerformed(evt);
            }
        });
        dataPemilihPanel.add(resetButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        pemilihTable.setBackground(new java.awt.Color(250, 250, 250));
        pemilihTable.setForeground(new java.awt.Color(51, 51, 51));
        pemilihTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NO", "NPM", "NAMA", "ANGKATAN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pemilihTable.setGridColor(new java.awt.Color(250, 250, 250));
        pemilihTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pemilihTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pemilihTable);

        dataPemilihPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 430, 230));
        jScrollPane2.getAccessibleContext().setAccessibleName("");

        searchButton.setBackground(new java.awt.Color(193, 158, 44));
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.setBorderPainted(false);
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        dataPemilihPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 3, 36)); // NOI18N
        jLabel9.setText("Data Pemilih");
        dataPemilihPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, -1));

        jLabel26.setText("NPM");
        dataPemilihPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel27.setText(":");
        dataPemilihPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin.png"))); // NOI18N
        dataPemilihPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(dataPemilihPanel, "card3");

        dataCalonPanel.setPreferredSize(new java.awt.Dimension(1192, 625));
        dataCalonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText(":");
        dataCalonPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 10, -1));

        noUrutField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noUrutFieldActionPerformed(evt);
            }
        });
        dataCalonPanel.add(noUrutField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 50, -1));

        jLabel17.setText("Nama");
        dataCalonPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 40, -1));

        namaCalonField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaCalonFieldActionPerformed(evt);
            }
        });
        dataCalonPanel.add(namaCalonField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, -1));

        visiMisiTextArea.setColumns(20);
        visiMisiTextArea.setRows(5);
        jScrollPane1.setViewportView(visiMisiTextArea);

        dataCalonPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, -1));

        jLabel18.setText("Visi & Misi");
        dataCalonPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 60, -1));

        updateCalonButton.setBackground(new java.awt.Color(51, 153, 0));
        updateCalonButton.setForeground(new java.awt.Color(255, 255, 255));
        updateCalonButton.setText("Update");
        updateCalonButton.setBorderPainted(false);
        updateCalonButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateCalonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCalonButtonActionPerformed(evt);
            }
        });
        dataCalonPanel.add(updateCalonButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        resetButton3.setBackground(new java.awt.Color(153, 0, 0));
        resetButton3.setForeground(new java.awt.Color(255, 255, 255));
        resetButton3.setText("Reset");
        resetButton3.setBorderPainted(false);
        resetButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButton3MouseClicked(evt);
            }
        });
        dataCalonPanel.add(resetButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        calonTable.setBackground(new java.awt.Color(250, 250, 250));
        calonTable.setForeground(new java.awt.Color(51, 51, 51));
        calonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NO URUT", "NAMA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        calonTable.setGridColor(new java.awt.Color(250, 250, 250));
        calonTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calonTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(calonTable);

        dataCalonPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 390, 117));

        fotoCalonField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoCalonField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dataCalonPanel.add(fotoCalonField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 110, 140));

        cariCalonButton2.setBackground(new java.awt.Color(193, 158, 44));
        cariCalonButton2.setForeground(new java.awt.Color(255, 255, 255));
        cariCalonButton2.setText("Search");
        cariCalonButton2.setBorderPainted(false);
        cariCalonButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cariCalonButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariCalonButton2ActionPerformed(evt);
            }
        });
        dataCalonPanel.add(cariCalonButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel28.setFont(new java.awt.Font("Imprint MT Shadow", 3, 36)); // NOI18N
        jLabel28.setText("Data Calon");
        dataCalonPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 380, -1));

        jLabel29.setText("No Urut");
        dataCalonPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 50, -1));

        jLabel31.setText(":");
        dataCalonPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 10, -1));

        jLabel32.setText(":");
        dataCalonPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 10, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin.png"))); // NOI18N
        dataCalonPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(dataCalonPanel, "card3");

        dataSuaraPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suaraTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "suara_id", "npm", "no_urut", "waktu"
            }
        ));
        jScrollPane4.setViewportView(suaraTable);

        dataSuaraPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 449, 410));

        jLabel20.setText("Calon 1 - Dylan");
        dataSuaraPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel21.setText("Calon 2 - Zhafran");
        dataSuaraPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        suaraCalon1Field.setEditable(false);
        suaraCalon1Field.setBackground(new java.awt.Color(250, 250, 250));
        suaraCalon1Field.setForeground(new java.awt.Color(51, 51, 51));
        dataSuaraPanel.add(suaraCalon1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 71, -1));

        suaraCalon2Field.setEditable(false);
        suaraCalon2Field.setBackground(new java.awt.Color(250, 250, 250));
        suaraCalon2Field.setForeground(new java.awt.Color(51, 51, 51));
        dataSuaraPanel.add(suaraCalon2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 71, -1));

        suaraCalon3Field.setEditable(false);
        suaraCalon3Field.setBackground(new java.awt.Color(250, 250, 250));
        suaraCalon3Field.setForeground(new java.awt.Color(51, 51, 51));
        dataSuaraPanel.add(suaraCalon3Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 71, -1));

        jLabel22.setText("Calon 3 - Evan");
        dataSuaraPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel30.setFont(new java.awt.Font("Imprint MT Shadow", 3, 36)); // NOI18N
        jLabel30.setText("Suara Masuk");
        dataSuaraPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin.png"))); // NOI18N
        dataSuaraPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(dataSuaraPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void npmPemilihFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npmPemilihFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npmPemilihFieldActionPerformed

    private void namaPemilihFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPemilihFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPemilihFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if (npmPemilihField.getText().equals("") && namaPemilihField.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Silahkan isi data yang ingin dicari");
        else {
            if (!npmPemilihField.getText().isEmpty()) {
                Koneksi kon = new Koneksi();
                ResultSet rs = null;
                DefaultTableModel model = (DefaultTableModel) pemilihTable.getModel();
                int i = 1;

                model.setRowCount(0);

                try {
                    rs = kon.getData("SELECT * FROM pemilih WHERE NPM ='" + npmPemilihField.getText() + "'");

                    if (rs.isBeforeFirst()) {
                        while (rs.next()) {
                            String npm = rs.getString("npm");
                            String angkatan = "20" + npm.substring(6, 8);
                            model.addRow(new Object[]{
                                i,
                                npm,
                                rs.getString("nama_pemilih"),
                                angkatan
                            });
                            i++;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Data tidak ditemukan", "Info", JOptionPane.INFORMATION_MESSAGE);
                        showPemilihTable();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                Koneksi kon = new Koneksi();
                ResultSet rs = null;
                DefaultTableModel model = (DefaultTableModel) pemilihTable.getModel();
                int i = 1;

                model.setRowCount(0);

                try {
                    rs = kon.getData("SELECT * FROM pemilih WHERE nama_pemilih LIKE '%" + namaPemilihField.getText() + "%'");

                    if (rs.isBeforeFirst()) {
                        while (rs.next()) {
                            String npm = rs.getString("npm");
                            String angkatan = "20" + npm.substring(6, 8);
                            model.addRow(new Object[]{
                                i,
                                npm,
                                rs.getString("nama_pemilih"),
                                angkatan
                            });
                            i++;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Data tidak ditemukan", "Info", JOptionPane.INFORMATION_MESSAGE);
                        showPemilihTable();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void noUrutFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noUrutFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noUrutFieldActionPerformed

    private void namaCalonFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaCalonFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaCalonFieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        homePanel.setVisible(true);
        tambahPemilihPanel.setVisible(false);
        dataPemilihPanel.setVisible(false);
        dataCalonPanel.setVisible(false);
        dataSuaraPanel.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
        homePanel.setVisible(true);
        tambahPemilihPanel.setVisible(false);
        dataPemilihPanel.setVisible(false);
        dataCalonPanel.setVisible(false);
        dataSuaraPanel.setVisible(false);
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        homePanel.setVisible(false);
        tambahPemilihPanel.setVisible(true);
        dataPemilihPanel.setVisible(false);
        dataCalonPanel.setVisible(false);
        dataSuaraPanel.setVisible(false);
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        homePanel.setVisible(false);
        tambahPemilihPanel.setVisible(false);
        dataPemilihPanel.setVisible(true);
        dataCalonPanel.setVisible(false);
        dataSuaraPanel.setVisible(false);

        showPemilihTable();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        homePanel.setVisible(false);
        tambahPemilihPanel.setVisible(false);
        dataPemilihPanel.setVisible(false);
        dataCalonPanel.setVisible(true);
        dataSuaraPanel.setVisible(false);

        showCalonTable();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        // TODO add your handling code here:
        homePanel.setVisible(false);
        tambahPemilihPanel.setVisible(false);
        dataPemilihPanel.setVisible(false);
        dataCalonPanel.setVisible(false);
        dataSuaraPanel.setVisible(true);

        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        DefaultTableModel model = (DefaultTableModel) suaraTable.getModel();

        model.setRowCount(0);

        try {
            rs = kon.getData("SELECT * FROM suara");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("suara_id"),
                    rs.getString("npm"),
                    rs.getString("no_urut"),
                    rs.getString("waktu")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Pastikan selalu menutup ResultSet setelah digunakan
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }

        String vote1;
        String vote2;
        String vote3;

        try {
            rs = kon.getData("SELECT COUNT(*) AS vote1 FROM suara WHERE no_urut = 1");

            if (rs.next()) {
                vote1 = rs.getString("vote1");
            } else {
                vote1 = "0";
            }
            suaraCalon1Field.setText(vote1);

            rs = kon.getData("SELECT COUNT(*) AS vote2 FROM suara WHERE no_urut = 2");

            if (rs.next()) {
                vote2 = rs.getString("vote2");
            } else {
                vote2 = "0";
            }
            suaraCalon2Field.setText(vote2);

            rs = kon.getData("SELECT COUNT(*) AS vote3 FROM suara WHERE no_urut = 3");

            if (rs.next()) {
                vote3 = rs.getString("vote3");
            } else {
                vote3 = "0";
            }
            suaraCalon3Field.setText(vote3);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }


    }//GEN-LAST:event_jPanel8MousePressed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        if (npmTextField.getText().equals("") || namaTextField.getText().equals("") || PasswordField.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Silahkan isi data pemilih terlebih dahulu");
        else if (npmTextField.getText().length() != 12) {
            JOptionPane.showMessageDialog(null, "Format NPM tidak sesuai");
        } else {
            pemilihClass pem = new pemilihClass();
            pem.setNpm(npmTextField.getText());
            pem.setNama_pemilih(namaTextField.getText());
            pem.setPassword_pemilih(PasswordField.getText());
            pem.setStatus(0);
            pem.insertPemilih();
            npmTextField.setText("");
            namaTextField.setText("");
            PasswordField.setText("");
        }
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        npmTextField.setText("");
        namaTextField.setText("");
        PasswordField.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void pemilihTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemilihTableMouseClicked
        // TODO add your handling code here:
        int row;
        row = pemilihTable.getSelectedRow();
        npmPemilihField.setText(pemilihTable.getValueAt(row, 1).toString());
        namaPemilihField.setText(pemilihTable.getValueAt(row, 2).toString());
        npmPemilihField.setEnabled(false);
    }//GEN-LAST:event_pemilihTableMouseClicked

    private void resetButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton2ActionPerformed
        // TODO add your handling code here:
        npmPemilihField.setText("");
        namaPemilihField.setText("");
        showPemilihTable();
        npmPemilihField.setEnabled(true);
    }//GEN-LAST:event_resetButton2ActionPerformed

    private void updatePemilihButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePemilihButtonActionPerformed
        // TODO add your handling code here:
        if (npmPemilihField.getText().equals("") || namaPemilihField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan lengkapi data yang ingin diperbarui");
        } else {
            pemilihClass pem = new pemilihClass();
            pem.setNpm(npmPemilihField.getText());
            pem.setNama_pemilih(namaPemilihField.getText());
            pem.updatePemilih();
            npmPemilihField.setText("");
            namaPemilihField.setText("");
            showPemilihTable();
            npmPemilihField.setEnabled(true);
        }
    }//GEN-LAST:event_updatePemilihButtonActionPerformed

    private void hapusPemilihButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemilihButtonActionPerformed
        // TODO add your handling code here:
        if (npmPemilihField.getText().equals("") || namaPemilihField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan lengkapi data yang ingin diperbarui");
        } else {
            pemilihClass pem = new pemilihClass();
            pem.setNpm(npmPemilihField.getText());
            pem.deletePemilih();
            npmPemilihField.setText("");
            namaPemilihField.setText("");
            showPemilihTable();
            npmPemilihField.setEnabled(true);
        }
    }//GEN-LAST:event_hapusPemilihButtonActionPerformed

    private void calonTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calonTableMouseClicked
        // TODO add your handling code here:
        int row;
        row = calonTable.getSelectedRow();

        Koneksi kon = new Koneksi();
        ResultSet rs = null;

        try {
            rs = kon.getData("SELECT * FROM calon WHERE no_urut = '" + calonTable.getValueAt(row, 0).toString() + "'");

            if (rs.next()) {
                noUrutField.setText(rs.getString("no_urut"));
                namaCalonField.setText(rs.getString("nama_calon"));
                visiMisiTextArea.setText(rs.getString("visi_misi"));
            } else {
                JOptionPane.showMessageDialog(null, "Data calon tidak ditemukan", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {

        }

        tampilFoto();
    }//GEN-LAST:event_calonTableMouseClicked

    private void resetButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButton3MouseClicked
        // TODO add your handling code here:
        noUrutField.setText("");
        namaCalonField.setText("");
        visiMisiTextArea.setText("");
        showCalonTable();

        fotoCalonField.setIcon(null);
    }//GEN-LAST:event_resetButton3MouseClicked

    private void cariCalonButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariCalonButton2ActionPerformed
        if (noUrutField.getText().equals("") && namaCalonField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan lengkapi data yang ingin dicari");
        } else if (!noUrutField.getText().isEmpty()) {
            Koneksi kon = new Koneksi();
            ResultSet rs = null;
            DefaultTableModel model = (DefaultTableModel) calonTable.getModel();

            model.setRowCount(0);

            try {
                rs = kon.getData("SELECT * FROM calon WHERE no_urut ='" + noUrutField.getText() + "'");

                if (rs.isBeforeFirst()) {
                    while (rs.next()) {
                        model.addRow(new Object[]{
                            rs.getString("no_urut"),
                            rs.getString("nama_calon")
                        });
                        namaCalonField.setText(rs.getString("nama_calon"));
                        visiMisiTextArea.setText(rs.getString("visi_misi"));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan", "Info", JOptionPane.INFORMATION_MESSAGE);
                    showCalonTable();
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            Koneksi kon = new Koneksi();
            ResultSet rs = null;
            DefaultTableModel model = (DefaultTableModel) calonTable.getModel();
            int i = 1;

            model.setRowCount(0);

            try {
                rs = kon.getData("SELECT * FROM calon WHERE nama_calon LIKE '%" + namaCalonField.getText() + "%'");

                if (rs.isBeforeFirst()) {
                    while (rs.next()) {
                        model.addRow(new Object[]{
                            rs.getString("no_urut"),
                            rs.getString("nama_calon")
                        });
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan", "Info", JOptionPane.INFORMATION_MESSAGE);
                    showCalonTable();
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        tampilFoto();
    }//GEN-LAST:event_cariCalonButton2ActionPerformed

    private void updateCalonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCalonButtonActionPerformed
        // TODO add your handling code here:
        calonClass cal = new calonClass();
        cal.setNoUrut(Integer.parseInt(noUrutField.getText()));
        cal.setNamaCalon(namaCalonField.getText());
        cal.setVisiMisi(visiMisiTextArea.getText());
        cal.updateCalon();
        showCalonTable();
    }//GEN-LAST:event_updateCalonButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(null, "Logout Success");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showPemilihTable() {
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        DefaultTableModel model = (DefaultTableModel) pemilihTable.getModel();

        model.setRowCount(0);

        try {
            rs = kon.getData("SELECT * FROM pemilih");
            int i = 1;
            while (rs.next()) {
                String npm = rs.getString("npm");
                String angkatan = "20" + npm.substring(6, 8);
                model.addRow(new Object[]{
                    i,
                    npm,
                    rs.getString("nama_pemilih"),
                    angkatan
                });
                i++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Pastikan selalu menutup ResultSet setelah digunakan
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }

    private void showCalonTable() {
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        DefaultTableModel model = (DefaultTableModel) calonTable.getModel();

        model.setRowCount(0);

        try {
            rs = kon.getData("SELECT * FROM calon");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("no_urut"),
                    rs.getString("nama_calon")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Pastikan selalu menutup ResultSet setelah digunakan
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }

    private void tampilFoto() {
        if (noUrutField.getText().equals("1")) {
            ImageIcon img = new ImageIcon("C:/code/semester 3/OOP/Projek/Peluit_Himatif_1/Peluit_Himatif/src/Image/140810220003.jpg");
            fotoCalonField.setIcon(img);
        } else if (noUrutField.getText().equals("2")) {
            ImageIcon img = new ImageIcon("C:/code/semester 3/OOP/Projek/Peluit_Himatif_1/Peluit_Himatif/src/Image/140810220007.jpg");
            fotoCalonField.setIcon(img);
        } else if (noUrutField.getText().equals("3")) {
            ImageIcon img = new ImageIcon("C:/code/semester 3/OOP/Projek/Peluit_Himatif_1/Peluit_Himatif/src/Image/140810220017.jpg");
            fotoCalonField.setIcon(img);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTable calonTable;
    private javax.swing.JButton cariCalonButton2;
    private javax.swing.JPanel dataCalonPanel;
    private javax.swing.JPanel dataPemilihPanel;
    private javax.swing.JPanel dataSuaraPanel;
    private javax.swing.JLabel fotoCalonField;
    private javax.swing.JButton hapusPemilihButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField namaCalonField;
    private javax.swing.JTextField namaPemilihField;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField noUrutField;
    private javax.swing.JTextField npmPemilihField;
    private javax.swing.JTextField npmTextField;
    private javax.swing.JTable pemilihTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetButton2;
    private javax.swing.JButton resetButton3;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField suaraCalon1Field;
    private javax.swing.JTextField suaraCalon2Field;
    private javax.swing.JTextField suaraCalon3Field;
    private javax.swing.JTable suaraTable;
    private javax.swing.JButton tambahButton;
    private javax.swing.JPanel tambahPemilihPanel;
    private javax.swing.JButton updateCalonButton;
    private javax.swing.JButton updatePemilihButton;
    private javax.swing.JTextArea visiMisiTextArea;
    // End of variables declaration//GEN-END:variables
}
